baseURL = "https://claudiarreyes.github.io/"
languageCode = "en-us"
title = "claudia.reyes@anu.edu.au"
description = "Research Projects by Claudia Reyes"
theme = "ananke"

[params]
  showFullPosts = true
  featured_image = "/images/clusterm67.jpg"
  disable_footer = true
  summaryLength = 1300
  mainSections = ["post"]
  custom_css = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[frontmatter]
  summary = [""]
